# Generated by Django 4.0.2 on 2022-02-14 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='air_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='anode_check',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='comission',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 52, 39, 382149, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='report',
            name='date_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='flue_gas_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='flue_gas_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='gas_conn_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='gas_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='gas_water_tightness_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='heat_carrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='maintenance_need_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='report',
            name='repairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='repairs_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='repairs_need_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='safety_systems_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='system_hydr_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='thermostat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='yes_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='boiler',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
