# Generated by Django 4.0.2 on 2022-02-20 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_address_report_air_check_report_anode_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 5, 41, 32, 810868, tzinfo=utc)),
        ),
    ]
