# Generated by Django 4.0.2 on 2022-04-17 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 6, 27, 0, 208906, tzinfo=utc)),
        ),
    ]
