# Generated by Django 4.0.2 on 2022-04-17 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_alter_invoice_customer_alter_line_invoice'),
        ('reports', '0008_alter_report_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='invoicing.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 6, 41, 16, 680576, tzinfo=utc)),
        ),
    ]
