# Generated by Django 4.0.2 on 2022-02-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_line_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='create_date',
        ),
    ]
