# Generated by Django 4.0.2 on 2022-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='vat_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='line',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='line',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
