# Generated by Django 4.0.2 on 2022-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_alter_customer_city_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_time',
            field=models.IntegerField(default=5),
        ),
    ]
